# Generated by Django 2.1.15 on 2021-07-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delicious',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
